### ISSUE TITLE
Add automatic purging of old data

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden-transport#14]
# Problem Description

The current setup has no data retention management. In our tests we discovered that the databse size can grow quickly.

## Tasks

- [ ] Decide on a cutoff period for old data (e.g. 2 weeks)
- [ ] Implement automatic purging of old event data 
- [ ] Add postgres autovacuum

**Comment by LefterisJP** [comment]
We should also make the cutoff period configurable. Guess depends a lot on the hardware specs (i.e. disk size) of the respective server
